# Generated by Django 4.2 on 2023-09-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='email',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='border',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='dark',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='data_dark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='data_light',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='light',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='scale',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='unit',
            field=models.CharField(default='mm', max_length=10),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='qr_code.qrcodetype'),
        ),
    ]
