# Generated by Django 4.2 on 2023-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0002_qrcodetype_remove_qrcode_email_qrcode_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='border',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='dark',
            field=models.CharField(blank=True, default='black', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='light',
            field=models.CharField(blank=True, default='white', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='scale',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='unit',
            field=models.CharField(blank=True, default='mm', max_length=10, null=True),
        ),
    ]
